### PR TITLE
 Updated the Readme file

### PR DESCRIPTION
**Pull request by aditimaurya**
I've updated all the latest scripts that have been introduced by the various contributors in this project. I've altered a few lines to make it more engaging and also did some minor changes in the attributes of the pages. I've included two new sections "how to use these scripts" and "license" to make it more user-friendly. 
( If you need some further changes then do let me know, I'll be happy to contribute .)

### CODE REVIEW

**Comment by PSNAppz** [comment]
@aditimaurya Great work :)

**Comment by PSNAppz** [comment]
@aditimaurya If you can add the Hacktoberfest guidelines here, it would be great.

**Comment by aditimaurya** [comment]
Sure, Sure !! I'll do it today.

**Review by PSNAppz — APPROVED** [review]
Nice work @aditimaurya :)

**Pull request merged**
